import React, { useState, useMemo } from 'react';
import JSZip from 'jszip';
import {
  Code,
  FileText,
  Layout,
  CheckCircle,
  Copy,
  Check,
  Shield,
  RefreshCw,
  Sparkles,
  Download,
  Smartphone,
  Tablet,
  Monitor,
  Package,
  ListChecks,
  AlertCircle,
  ArrowRight,
  RotateCcw,
  FolderTree,
} from 'lucide-react';
import { FinalArtifact } from '../../types/agent';
import { LiveSandbox } from './LiveSandbox';
import { FileTreeNavigator } from './FileTreeNavigator';

interface OutputPreviewProps {
  artifact: FinalArtifact | null;
  pipelineRunning: boolean;
  onRequestRepair?: (error: string) => void;
  onStartContractCompletion?: (specificModule?: string) => void;
  onResetProject?: () => void;
}

export const OutputPreview: React.FC<OutputPreviewProps> = ({
  artifact,
  pipelineRunning,
  onRequestRepair,
  onStartContractCompletion,
  onResetProject,
}) => {
  const [activeTab, setActiveTab] = useState<'artifact' | 'files' | 'code' | 'contract' | 'markdown' | 'audit'>('artifact');
  const [copied, setCopied] = useState(false);
  const [viewportMode, setViewportMode] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const [isExporting, setIsExporting] = useState(false);

  // Compute multi-file project structure
  const projectFiles = useMemo(() => {
    if (!artifact?.codeSnippet) return {};
    if (artifact.projectFiles && Object.keys(artifact.projectFiles).length > 0) {
      return artifact.projectFiles;
    }
    const compName = artifact.architectSpec?.componentName || 'App';
    return {
      [`src/${compName}.tsx`]: artifact.codeSnippet,
      'src/main.tsx': `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport ${compName} from './${compName}';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <${compName} />\n  </React.StrictMode>\n);\n`,
      'src/index.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  background-color: #070b14;\n  color: #f1f5f9;\n  font-family: system-ui, sans-serif;\n}\n`,
      'package.json': JSON.stringify(
        {
          name: compName.toLowerCase(),
          private: true,
          version: '1.0.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc && vite build',
            preview: 'vite preview',
          },
          dependencies: {
            react: '^18.3.1',
            'react-dom': '^18.3.1',
            'lucide-react': '^0.460.0',
          },
          devDependencies: {
            '@types/react': '^18.3.12',
            '@types/react-dom': '^18.3.1',
            '@vitejs/plugin-react': '^4.3.4',
            tailwindcss: '^3.4.15',
            typescript: '^5.6.3',
            vite: '^6.0.1',
          },
        },
        null,
        2
      ),
      'index.html': `<!DOCTYPE html>\n<html lang="en" class="dark">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${compName}</title>\n  </head>\n  <body class="bg-slate-950 text-slate-100">\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
      'README.md': artifact.markdownReport || `# ${compName}\n\nGenerated by Agentic Command Center with Hermes Gateway.\n`,
    };
  }, [artifact]);

  if (!artifact && !pipelineRunning) {
    return null;
  }

  const handleCopyCode = () => {
    if (artifact?.codeSnippet) {
      navigator.clipboard.writeText(artifact.codeSnippet);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  const handleDownloadTsx = () => {
    if (!artifact?.codeSnippet) return;
    const blob = new Blob([artifact.codeSnippet], { type: 'text/typescript;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${artifact.architectSpec?.componentName || 'App'}.tsx`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadZip = async () => {
    if (!artifact?.codeSnippet) return;
    setIsExporting(true);

    try {
      const zip = new JSZip();
      const compName = artifact.architectSpec?.componentName || 'App';

      // 1. App Component
      zip.file(`src/${compName}.tsx`, artifact.codeSnippet);

      // 2. Main Entry
      zip.file(
        'src/main.tsx',
        `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport ${compName} from './${compName}';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><${compName} /></React.StrictMode>);\n`
      );

      // 3. CSS
      zip.file('src/index.css', `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody { background-color: #0b0f19; color: #f1f5f9; }\n`);

      // 4. package.json
      const pkgJson = {
        name: compName.toLowerCase(),
        private: true,
        version: "1.0.0",
        type: "module",
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview"
        },
        dependencies: {
          react: "^18.3.1",
          "react-dom": "^18.3.1",
          "lucide-react": "^0.460.0"
        },
        devDependencies: {
          "@types/react": "^18.3.12",
          "@types/react-dom": "^18.3.1",
          "@vitejs/plugin-react": "^4.3.4",
          tailwindcss: "^3.4.15",
          typescript: "^5.6.3",
          vite: "^6.0.1"
        }
      };
      zip.file('package.json', JSON.stringify(pkgJson, null, 2));

      // 5. index.html
      zip.file(
        'index.html',
        `<!DOCTYPE html>\n<html lang="en" class="dark">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${compName}</title>\n</head>\n<body class="bg-slate-950 text-slate-100">\n  <div id="root"></div>\n  <script type="module" src="/src/main.tsx"></script>\n</body>\n</html>\n`
      );

      // 6. README.md
      zip.file('README.md', artifact.markdownReport || `# ${compName}\n\nGenerated with Agentic Command Center.`);

      const content = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${compName}-project.zip`;
      link.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Error creating ZIP export:', err);
    } finally {
      setIsExporting(false);
    }
  };

  const getViewportWidth = () => {
    switch (viewportMode) {
      case 'mobile':
        return 'max-w-[375px]';
      case 'tablet':
        return 'max-w-[768px]';
      default:
        return 'w-full';
    }
  };

  const completedCount = artifact?.contractChecklist?.filter(c => c.status === 'completed').length || 0;
  const totalCount = artifact?.contractChecklist?.length || 0;
  const completionPercentage = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 100;

  return (
    <div className="w-full rounded-2xl border border-slate-800 bg-[#070b14] shadow-2xl overflow-hidden flex flex-col min-h-[480px]">
      {/* Top Header with Tabs */}
      <div className="flex flex-wrap items-center justify-between px-6 py-3 bg-slate-950 border-b border-slate-800/80 gap-3">
        <div className="flex items-center gap-2">
          <Layout className="w-4 h-4 text-cyan-400" />
          <span className="text-xs font-bold uppercase tracking-wider text-slate-200 font-mono">
            Entregables & Salida del Pipeline
          </span>
          {artifact?.repairLoopTriggered && (
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-rose-950/80 text-rose-300 border border-rose-800">
              Auto-Reparado por Auditor
            </span>
          )}
        </div>

        {/* Action Buttons: Complete Contract & Reset */}
        <div className="flex items-center gap-2">
          {onStartContractCompletion && artifact && (
            <button
              onClick={() => onStartContractCompletion()}
              className="px-3 py-1.5 rounded-lg bg-emerald-950/80 hover:bg-emerald-900 border border-emerald-600 text-emerald-300 hover:text-white text-xs font-bold transition-all shadow-[0_0_12px_rgba(16,185,129,0.3)] flex items-center gap-1.5"
              title="Volver al principio para construir las partes del contrato que faltan con Gemini 3.8 Flash"
            >
              <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
              <span>Completar Módulos Faltantes con IA</span>
            </button>
          )}

          {onResetProject && (
            <button
              onClick={onResetProject}
              className="px-2.5 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-400 hover:text-slate-200 text-xs font-medium transition-colors flex items-center gap-1"
              title="Comenzar un nuevo proyecto desde cero"
            >
              <RotateCcw className="w-3 h-3 text-slate-400" />
              <span className="hidden sm:inline">Nuevo</span>
            </button>
          )}

          {/* Tab Selection Buttons */}
          <div className="flex items-center gap-1 bg-slate-900/80 p-1 rounded-xl border border-slate-800 text-xs">
            <button
              onClick={() => setActiveTab('artifact')}
              className={`px-3 py-1 rounded-lg font-medium transition-colors flex items-center gap-1.5 ${
                activeTab === 'artifact'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Layout className="w-3.5 h-3.5" />
              <span>Artefacto UI</span>
            </button>
            <button
              onClick={() => setActiveTab('files')}
              className={`px-3 py-1 rounded-lg font-medium transition-colors flex items-center gap-1.5 ${
                activeTab === 'files'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FolderTree className="w-3.5 h-3.5" />
              <span>Archivos ({Object.keys(projectFiles).length})</span>
            </button>
            <button
              onClick={() => setActiveTab('code')}
              className={`px-3 py-1 rounded-lg font-medium transition-colors flex items-center gap-1.5 ${
                activeTab === 'code'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Code className="w-3.5 h-3.5" />
              <span>Código Snippet</span>
            </button>
            <button
              onClick={() => setActiveTab('contract')}
              className={`px-3 py-1 rounded-lg font-medium transition-colors flex items-center gap-1.5 ${
                activeTab === 'contract'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <ListChecks className="w-3.5 h-3.5" />
              <span>Contrato ({completedCount}/{totalCount})</span>
            </button>
            <button
              onClick={() => setActiveTab('markdown')}
              className={`px-3 py-1 rounded-lg font-medium transition-colors flex items-center gap-1.5 ${
                activeTab === 'markdown'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span className="hidden md:inline">Blueprint</span>
            </button>
            <button
              onClick={() => setActiveTab('audit')}
              className={`px-3 py-1 rounded-lg font-medium transition-colors flex items-center gap-1.5 ${
                activeTab === 'audit'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Shield className="w-3.5 h-3.5" />
              <span>Auditoría QC</span>
            </button>
          </div>
        </div>
      </div>

      {/* Body Content */}
      <div className="flex-1 p-4 sm:p-6 overflow-y-auto">
        {/* Loading State during pipeline */}
        {pipelineRunning && !artifact && (
          <div className="flex flex-col items-center justify-center py-20 text-center space-y-3">
            <RefreshCw className="w-8 h-8 text-cyan-400 animate-spin" />
            <h4 className="text-sm font-bold text-white font-mono">
              Generando artefacto con el encadenamiento de LLMs en tiempo real...
            </h4>
            <p className="text-xs text-slate-400 max-w-sm">
              El Arquitecto está proyectando el blueprint, El Worker escribiendo el código React y El Auditor escaneando.
            </p>
          </div>
        )}

        {/* TAB 1: EXECUTABLE LIVE SANDBOX */}
        {artifact && activeTab === 'artifact' && (
          <div className="space-y-4">
            {/* Sandbox Toolbar: Responsive switcher & Exports */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs text-slate-400 pb-2 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <span className="flex items-center gap-1.5 font-medium text-slate-300">
                  <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
                  Renderizado en vivo en sandbox aislado:
                </span>
                {/* Responsive Viewport Switcher */}
                <div className="flex items-center gap-1 bg-slate-900 p-0.5 rounded-lg border border-slate-800">
                  <button
                    onClick={() => setViewportMode('desktop')}
                    className={`p-1 rounded ${viewportMode === 'desktop' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'}`}
                    title="Vista de escritorio (100%)"
                  >
                    <Monitor className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={() => setViewportMode('tablet')}
                    className={`p-1 rounded ${viewportMode === 'tablet' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'}`}
                    title="Vista tablet (768px)"
                  >
                    <Tablet className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={() => setViewportMode('mobile')}
                    className={`p-1 rounded ${viewportMode === 'mobile' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'}`}
                    title="Vista móvil (375px)"
                  >
                    <Smartphone className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* 1-Click Export Actions */}
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadTsx}
                  className="px-2.5 py-1 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-white border border-slate-800 text-[11px] font-semibold flex items-center gap-1.5 transition-colors"
                  title="Descargar solo el archivo de componente (.tsx)"
                >
                  <Download className="w-3 h-3 text-cyan-400" />
                  <span>Descargar .tsx</span>
                </button>
                <button
                  onClick={handleDownloadZip}
                  disabled={isExporting}
                  className="px-3 py-1 rounded-lg bg-cyan-950 hover:bg-cyan-900 text-cyan-300 border border-cyan-800 text-[11px] font-bold flex items-center gap-1.5 transition-colors shadow-sm"
                  title="Descargar proyecto completo listo para npm run dev (.zip)"
                >
                  <Package className="w-3 h-3 text-cyan-400" />
                  <span>{isExporting ? 'Generando ZIP...' : 'Exportar Proyecto (.zip)'}</span>
                </button>
              </div>
            </div>

            {/* The Live Sandboxed Iframe Runner with Responsive Center Frame */}
            <div className="flex justify-center transition-all">
              <div className={`w-full ${getViewportWidth()} transition-all duration-300`}>
                <LiveSandbox
                  codeSnippet={artifact.codeSnippet}
                  onRequestRepair={onRequestRepair}
                />
              </div>
            </div>
          </div>
        )}

        {/* TAB 1.5: MULTI-FILE PROJECT EXPLORER */}
        {artifact && activeTab === 'files' && (
          <div className="space-y-3 animate-[fadeIn_0.2s_ease-out]">
            <FileTreeNavigator
              files={projectFiles}
              componentName={artifact.architectSpec?.componentName || 'App'}
            />
          </div>
        )}

        {/* TAB 2: CODE SNIPPET (EXACT SOURCE CURRENTLY RUNNING) */}
        {artifact && activeTab === 'code' && (
          <div className="relative">
            <div className="flex items-center justify-between pb-3 text-xs text-slate-400 font-mono">
              <span>Código React + TypeScript ejecutándose en el Live Sandbox ({artifact.codeSnippet.split('\n').length} líneas):</span>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadTsx}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700 text-xs font-semibold transition-colors"
                >
                  <Download className="w-3.5 h-3.5 text-cyan-400" />
                  Descargar .tsx
                </button>
                <button
                  onClick={handleCopyCode}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold transition-colors shadow-sm"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-slate-950" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? '¡Copiado!' : 'Copiar Código'}
                </button>
              </div>
            </div>

            <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-mono text-cyan-200 overflow-x-auto leading-relaxed max-h-[480px] selection:bg-cyan-500/30">
              <code>{artifact.codeSnippet}</code>
            </pre>
          </div>
        )}

        {/* TAB 2.5: CONTRACT CHECKLIST & COMPLETION STATUS */}
        {artifact && activeTab === 'contract' && (
          <div className="space-y-5 animate-[fadeIn_0.2s_ease-out]">
            {/* Header Status Card */}
            <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono font-bold uppercase tracking-wider text-cyan-400">
                    Control de Contrato de Software
                  </span>
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold uppercase ${
                      completionPercentage === 100
                        ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                        : 'bg-amber-950 text-amber-300 border border-amber-800'
                    }`}
                  >
                    {completionPercentage}% Cumplido
                  </span>
                </div>
                <h3 className="text-base font-bold text-white mt-1">
                  {artifact.architectSpec?.componentName || 'Componente'} · Matriz de Entrega
                </h3>
                <p className="text-xs text-slate-400 mt-1">
                  {completedCount} de {totalCount} módulos implementados y verificados.
                  {totalCount - completedCount > 0
                    ? ` Quedan ${totalCount - completedCount} módulos pendientes para cumplimiento total.`
                    : ' ¡Todos los módulos del contrato han sido verificados!'}
                </p>
              </div>

              {/* Action Button: Return to Complete Contract */}
              {onStartContractCompletion && (
                <button
                  type="button"
                  onClick={() => onStartContractCompletion()}
                  className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-bold text-xs flex items-center gap-2 shadow-[0_0_15px_rgba(16,185,129,0.3)] transition-all shrink-0 self-start sm:self-auto"
                >
                  <Sparkles className="w-4 h-4 text-slate-950" />
                  <span>Construir Partes Faltantes</span>
                  <ArrowRight className="w-4 h-4 text-slate-950" />
                </button>
              )}
            </div>

            {/* Progress Bar */}
            <div className="w-full bg-slate-900 rounded-full h-2.5 overflow-hidden border border-slate-800">
              <div
                className="bg-gradient-to-r from-cyan-500 to-emerald-400 h-2.5 rounded-full transition-all duration-500"
                style={{ width: `${completionPercentage}%` }}
              />
            </div>

            {/* Modules List: Completed vs Pending */}
            <div className="space-y-3">
              <div className="text-xs font-mono uppercase tracking-wider text-slate-400 font-semibold flex items-center justify-between">
                <span>Desglose de Módulos del Contrato:</span>
                <span className="text-[11px] text-slate-500 font-normal">
                  Los módulos pendientes pueden integrarse incrementalmente con Gemini 3.8
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {artifact.contractChecklist && artifact.contractChecklist.length > 0 ? (
                  artifact.contractChecklist.map((item) => (
                    <div
                      key={item.id}
                      className={`p-3.5 rounded-xl border flex items-start justify-between gap-3 transition-all ${
                        item.status === 'completed'
                          ? 'bg-slate-900/40 border-slate-800/80 hover:border-emerald-500/40'
                          : 'bg-amber-950/20 border-amber-900/50 hover:border-amber-700/80'
                      }`}
                    >
                      <div className="flex items-start gap-2.5 min-w-0">
                        {item.status === 'completed' ? (
                          <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                        ) : (
                          <AlertCircle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                        )}
                        <div className="min-w-0">
                          <div className="flex items-center gap-2">
                            <h5
                              className={`text-xs font-bold truncate ${
                                item.status === 'completed' ? 'text-slate-200' : 'text-amber-200'
                              }`}
                            >
                              {item.name}
                            </h5>
                          </div>
                          <p className="text-[11px] text-slate-400 mt-0.5 leading-relaxed line-clamp-2">
                            {item.details}
                          </p>
                        </div>
                      </div>

                      <div className="shrink-0">
                        {item.status === 'completed' ? (
                          <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-emerald-950 text-emerald-400 border border-emerald-800">
                            Listo ✓
                          </span>
                        ) : onStartContractCompletion ? (
                          <button
                            type="button"
                            onClick={() => onStartContractCompletion(item.name)}
                            className="px-2.5 py-1 rounded-lg bg-amber-950 hover:bg-amber-900 text-amber-300 hover:text-white border border-amber-700/80 text-[10px] font-bold font-mono transition-colors flex items-center gap-1 shadow-sm"
                            title="Construir e integrar este módulo específico con El Worker"
                          >
                            <Sparkles className="w-3 h-3 text-amber-400" />
                            <span>Construir</span>
                          </button>
                        ) : (
                          <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-amber-950 text-amber-400 border border-amber-800">
                            Pendiente
                          </span>
                        )}
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="col-span-2 p-6 rounded-xl bg-slate-900/40 border border-slate-800 text-center text-xs text-slate-400 font-mono">
                    Todos los módulos iniciales del contrato están cubiertos.
                  </div>
                )}
              </div>
            </div>

            {/* Bottom Callout: Incremental Full Contract Builder */}
            {onStartContractCompletion && (
              <div className="p-4 rounded-xl bg-gradient-to-r from-cyan-950/40 via-indigo-950/40 to-slate-900 border border-cyan-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400 shrink-0">
                    <ListChecks className="w-4 h-4" />
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-white">
                      ¿Faltan partes de código por implementar para cumplir todo el contrato?
                    </h4>
                    <p className="text-[11px] text-slate-300 mt-0.5">
                      Vuelve al principio para que El Clarificador, El Arquitecto y El Worker ensamblen
                      los módulos faltantes sobre el código existente sin perder lo ya implementado.
                    </p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => onStartContractCompletion()}
                  className="px-4 py-2 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-colors shrink-0 flex items-center gap-1.5 shadow-[0_0_12px_rgba(6,182,212,0.3)]"
                >
                  <span>Volver al Principio y Construir</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            )}
          </div>
        )}

        {/* TAB 3: MARKDOWN REPORT & ARCHITECT BLUEPRINT */}
        {artifact && activeTab === 'markdown' && (
          <div className="rounded-xl border border-slate-800 bg-slate-950 p-6 text-xs text-slate-300 leading-relaxed font-sans max-h-[480px] overflow-y-auto space-y-4">
            <div className="prose prose-invert max-w-none">
              <pre className="whitespace-pre-wrap font-sans text-xs text-slate-300">
                {artifact.markdownReport}
              </pre>
            </div>
          </div>
        )}

        {/* TAB 4: AUDIT QC REPORT */}
        {artifact && activeTab === 'audit' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between p-4 rounded-xl bg-emerald-950/20 border border-emerald-800/60">
              <div className="flex items-center gap-3">
                <CheckCircle className="w-6 h-6 text-emerald-400" />
                <div>
                  <h4 className="text-sm font-bold text-white">Certificación de Calidad del Auditor</h4>
                  <p className="text-xs text-slate-400">
                    Inspección realizada por Agente 4 (El Verificador / Auditor).
                  </p>
                </div>
              </div>
              <div className="text-right">
                <div className="text-xl font-mono font-bold text-emerald-400">{artifact.auditScore} / 100</div>
                <div className="text-[10px] text-slate-500 font-mono">Status: Production Verified</div>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
              <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
                <div className="font-semibold text-slate-200">1. Verificación de Tipos & Compilabilidad</div>
                <p className="text-slate-400 text-[11px]">
                  Código autocontenido con `export default function`. Transpila limpiamente en Babel Standalone.
                </p>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
                <div className="font-semibold text-slate-200">2. Seguridad & Aislamiento</div>
                <p className="text-slate-400 text-[11px]">
                  Ejecutado en Iframe Sandboxed con aislamiento de contexto y sin acceso a cookies principales.
                </p>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
                <div className="font-semibold text-slate-200">3. Accesibilidad & Estilos Tailwind</div>
                <p className="text-slate-400 text-[11px]">
                  Clases utilitarias de Tailwind validadas, esquema responsivo y paleta de contraste compatible.
                </p>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
                <div className="font-semibold text-slate-200">4. Estado del Bucle de Reparación</div>
                <p className="text-slate-400 text-[11px]">
                  {artifact.repairLoopTriggered
                    ? 'Bucle de Auto-Reparación ejecutado exitosamente con parche validado.'
                    : 'Paso directo sin necesidad de reintentos.'}
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
